version: '3.8'

services:
  runner:
    build: .
    restart: always
    environment:
      - ORG=<organization-name>
      - REG_TOKEN=<reg-token-for-self-hosted-runner>
      - NAME=<runner-name>
      - LABELS=<runner-labels>
      - RUNNERGROUP=<runner-group>
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M